### ISSUE TITLE
Add in bootstrap CI code from Jacob

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [NOAA-EMC/emcpy#14]
See here on Hera
/scratch2/NCEPDEV/fv3-cam/Jacob.Carley/rtma/obfits/stats/bootstrap_ci.py

Jacob Carley has graciously provided this code as a contribution to emcpy, need to make sure it fits pep8 compliance and put it in stats.py and add a test, etc.

**Comment by aerorahul** [comment]
From MIT. I think I have seen this for very low sample sizes. 
Neat.

**Comment by EdwardSafford-NOAA** [comment]
@CoryMartin-NOAA I can take this on if you like.  I'm off next week but could start work ~11/29.

**Comment by CoryMartin-NOAA** [comment]
@EdwardSafford-NOAA that sounds great, thanks in advance!

**Comment by EdwardSafford-NOAA** [comment]
Closed with PR #85
