### ISSUE TITLE
Cartopy files for Hera and other platforms

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [NOAA-EMC/emcpy#15]
Need to copy shapefiles somewhere and then point to them in `cartopy.config['pre_existing_data_dir']`

How to best handle this? Can't really put all of the shape files in this repo?

Add a download script to place them somewhere and set this variable to be relative to the cartopy install directory in a virtual env?

**Comment by aerorahul** [comment]
I think we should provide instructions rather than a script to get the files.
Then we should instruct how to define/set environment variable that `cartopy.config` can understand.  It looks in the usual places, so may be instruct to create soft links from the files to the expected location.

**Comment by CoryMartin-NOAA** [comment]
https://scitools.org.uk/cartopy/docs/v0.14/cartopy.html for details

**Comment by CoryMartin-NOAA** [comment]
https://github.com/SciTools/cartopy/blob/master/tools/cartopy_feature_download.py to download the data
