### ISSUE TITLE
Add vertical plot class 

### ISSUE THREAD

**Issue by EdwardSafford-NOAA** [NOAA-EMC/emcpy#50]
Add a vertical plot class to src/emcpy/plots.py.  This will support (or maybe replace?) [PyGSI #58](https://github.com/NOAA-EMC/PyGSI/issues/58).

**Comment by EdwardSafford-NOAA** [comment]
Hmm.  I don't seem to be able to assign myself to this issue.  @CoryMartin-NOAA  or @kevindougherty-noaa can you make that happen?

**Comment by EdwardSafford-NOAA** [comment]
I'm at an impasse with the emcpy package.  I don't understand how the test scripts are properly run on hera.  I asked Kevin how he runs the package and he indicated a specific conda environment (UFO) which I have loaded successfully.  But when I try to run any of the test scripts (i.e. >python test_utils.py) the response is:
```
Fatal Python error: init_sys_streams: can't initialize sys standard streams
AttributeError: module 'io' has no attribute 'OpenWrapper'

Current thread 0x00007fc224dae740 (most recent call first):
Aborted
```
I dropped that error into google and the suggestion I got was to unset my PYTHONPATH variable.  Doing that changed the error response to this:
```
Traceback (most recent call last):
  File "test_utils.py", line 1, in <module>
    from emcpy.utils import float10Power, roundNumber
ModuleNotFoundError: No module named 'emcpy'
```
So that's not the answer.  Will continue to flounder.

**Comment by CoryMartin-NOAA** [comment]
what is your `$PYTHONPATH` set to before unsetting it? Also, you need to have `$PYTHONPATH` point to your clone of emcpy, otherwise it is expected that you will get the last error you pasted.

`$PYTHONPATH` works just like `$PATH` or `$LD_LIBRARY_PATH`, it tells python where to find python libraries besides the default places.

Kevin has an environment that he created that works for him, but I've yet to have a more generic one working on Hera yet, but everything works great on Orion. @aerorahul is working on making something work on Hera though.

**Comment by EdwardSafford-NOAA** [comment]
@CoryMartin-NOAA progress.  I had my $PYTHONPATH set to 

`:/scratch1/NCEPDEV/da/Edward.Safford/noscrub/PyGSI:/scratch1/NCEPDEV/da/Edward.Safford/noscrub/emcpy:/scratch1/NCEPDEV/da/Edward.Safford/noscrub/emcpy/src/emcpy `

but what I needed was 

`:/scratch1/NCEPDEV/da/Edward.Safford/noscrub/PyGSI:/scratch1/NCEPDEV/da/Edward.Safford/noscrub/emcpy:/scratch1/NCEPDEV/da/Edward.Safford/noscrub/emcpy/src`

Now when I run >python test_utils.py the reply is
```
qt.qpa.screen: QXcbConnection: Could not connect to display localhost:11.0
Could not connect to any X display.
```
Which I understand.  I'll have another go at X forwarding, though I've been unsuccessful with that on hera heretofore.

**Comment by CoryMartin-NOAA** [comment]
@EdwardSafford-NOAA great! There are ways around the x window forwarding, in fact I think we need to have this for batch plotting. Basically anywhere that 'matplotlib.pyplot' is imported you need instead:
```
import matplotlib
matplotlib.use('agg')
import matplotlib.pyplot as plt
```

The default renderer for matplotlib (qt) needs x-window for some reason, but agg does not.

**Comment by EdwardSafford-NOAA** [comment]
@CoryMartin-NOAA that's sure handy to know, thanks!

I'm curious though I get that x-window complaint when I'm trying to run the test_utils.py script (using >python test_utils.py), which imports some components from src/emcpy/utils.py.  But neither of those scripts import matplotlib.  What am I missing?

**Comment by CoryMartin-NOAA** [comment]
I think it's because when you import emcpy, you are implicitly importing emcpy.plots also because of this file:
https://github.com/NOAA-EMC/emcpy/blob/develop/src/emcpy/__init__.py

This is probably less than ideal, but not yet an expert enough on python packages to know the best way to set up these __init__.py files.

**Comment by EdwardSafford-NOAA** [comment]
Ah, I see.  Thanks again -- it would have taken me a **long** time to figure that out on my own.  I've made those import matplotlib changes to both src/emcpy/plots/create_map.py and create_plot.py.  The test scripts now run without generating any output.

**Comment by EdwardSafford-NOAA** [comment]
Question.  I found this in emcpy/plots/create_plot.py:

```
31         for obj in plot_list:
 32             try:
 33                 plot_dict[obj.plottype](obj)
 34             except KeyError:
 35                 raise TypeError(f'{obj} is not a valid plot type.' +
 36                                 'Current plot types supported are:\n' +
 37                                 f'{" | ".join(feature_dict.keys())}"')
```

I think feature_dict on line 37 should be plot_dict instead.  If I'm right, I can fix it as part of this issue.

**Comment by kevindougherty-noaa** [comment]
@EdwardSafford-NOAA Yes, it looks like it should be plot_dict. Good catch. I'm okay with you fixing it in this issue.

**Comment by EdwardSafford-NOAA** [comment]
I will make it so.

**Comment by EdwardSafford-NOAA** [comment]
@kevindougherty-noaa  @CoryMartin-NOAA  After some study and experimentation I think I can modify the existing LinePlot class to accomplish what we need for vertical plots.  I don't see any dependencies within the emcpy package that would prohibit changes to LinePlot.  Are there dependencies/plans I don't know about, or other reasons whey LinePlot should not be changed?

**Comment by CoryMartin-NOAA** [comment]
@EdwardSafford-NOAA I agree, LinePlot should be made to be generic enough to handle any case that is a 'line plot', after all a vertical profile is just a line plot where X is data and Y is height/pressure. Alternatively, 'Profile' could be a subclass of LinePlot if we think that would be handy for the general user?

**Comment by kevindougherty-noaa** [comment]
@EdwardSafford-NOAA I was goin to suggest exactly what @CoryMartin-NOAA just did. If you can make Profile a subclass of LinePlot that would ideal.

**Comment by EdwardSafford-NOAA** [comment]
@CoryMartin-NOAA @kevindougherty-noaa I can do that.  Here's what I'd like to do first though to the LinePlot constructor (with associated changes to _lineplot())
- change the x and y lists to lists of lists allowing a plot to be n number of lines rather than just one
- add a list of labels as optional arguments (allowing a label per line)
- add optional switch to generate a legend (that might be better applied to CreatePlot())

If you're good with those ideas I can start a new issue to make the changes.

**Comment by CoryMartin-NOAA** [comment]
@EdwardSafford-NOAA those sound good to me. `CreatePlot` is generic, right? We might want a 'legend' if it is a scatter plot with multiple points/symbols/colors, so I'm good with putting the legend there.

**Comment by EdwardSafford-NOAA** [comment]
@CoryMartin-NOAA yes CreatePlot() is the generic function that plots the plot object.  I'll open a new issue and reiterate the plan there.

**Comment by EdwardSafford-NOAA** [comment]
I'm closing this issue.  As my understanding of python and this package have grown, vertical plots per se are not really different from line plots.  Vertical plots will require a few new capabilities which I'll add to the CreatePlot class under a new issue.
