### ISSUE TITLE
Expand LinePlot and CreatePlot classes

### ISSUE THREAD

**Issue by EdwardSafford-NOAA** [NOAA-EMC/emcpy#56]
Expand the LinePlot (in plot/plot.py) constructor and make associated changes to the CreatePlot class (in plot/create_plot.py) to add additional options to line plots.  Specific changes include:

- change the x and y input lists to lists of lists, allowing a plot to be n number of lines rather than just a single line
- add a list of labels as optional arguments (allowing a label per line)
- add optional switch to generate a legend.  This will be done in the CreatePlot class so as to enable legends in LinePlot as well as other classes of plot objects.

**Comment by EdwardSafford-NOAA** [comment]
It's probably also worth mentioning that I've started a little test_plot.py file that I'm using for my development.  I note that there are other test routines in emcpy/test and can include that file with this issue.

**Comment by EdwardSafford-NOAA** [comment]
I missed seeing that create_plot.py already has an add_legend() routine so that's all set.  Here's some output from my test_plot driver using the modified LinePlot class:

![test_line_plot](https://user-images.githubusercontent.com/62339196/134036712-f81366a2-447e-4c35-bb28-6f076024ded6.png)

**Comment by CoryMartin-NOAA** [comment]
@EdwardSafford-NOAA there's a way to create the y-axis in log space in matplotlib, but it can be a bit clunky. It would be great if we could add an option for `log` for when things are plotted in pressure.

**Comment by EdwardSafford-NOAA** [comment]
@CoryMartin-NOAA Ok I'll look into it.

**Comment by CoryMartin-NOAA** [comment]
> @CoryMartin-NOAA Ok I'll look into it.

@kevindougherty-noaa might have suggestions, from what I can remember, it's "easy" to plot in log Y but then the labeling is formatted weird like `10^3`, and need to manually specify tick marks.

**Comment by kevindougherty-noaa** [comment]
@CoryMartin-NOAA @EdwardSafford-NOAA `ax.set_yscale()` may be the way to go. Could be easily added as a new method. https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.set_yscale.html

**Comment by EdwardSafford-NOAA** [comment]
@CoryMartin-NOAA I see what you meant about labeling with a log scale.  It's a bit erratic.  This proves the concept but it still needs a bit of work:

![test_line_log_scale](https://user-images.githubusercontent.com/62339196/134055069-039fa23f-48ad-4216-a02e-b2e3c2f28973.png)

**Comment by CoryMartin-NOAA** [comment]
@EdwardSafford-NOAA yep, and also when it is pressure, we want `invert_yaxis()` or something similar to that so that larger values are at the bottom.

**Comment by EdwardSafford-NOAA** [comment]
Next iteration, log scale, inverted y axis:

![test_line_log_scale(1)](https://user-images.githubusercontent.com/62339196/134177220-c9889bb3-f9d1-4bf9-83c6-426107d9723e.png)

**Comment by EdwardSafford-NOAA** [comment]
I'm going to close this issue.  As my understanding of both python and the emcpy package have grown I don't see the need for the work as I had outlined it in this issue.  Vertical/profile plots do need a few additional capabilities for which I'll open a new, specific issue and submit a PR from there.
