### ISSUE TITLE
Density scatter needs to be more robust

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [NOAA-EMC/emcpy#70]
If you set `plotobj.density = True` but do not set things like `plotobj.bins = 10` and `plotobj.sort = True`, the code will fail. This needs to be more robust and handle defaults just by setting `density = True`.

**Comment by kevindougherty-noaa** [comment]
@CoryMartin-NOAA the `density_scatter()` method needs to be called to change everything to the appropriate settings. `obj.density = False` is needed to determine that it is not a density plot in `create_plots.py`. i.e:

```
x=1
y=1

obj = Scatter(x,y)
obj.__dict__
```
produces:
```
{'plot_ax': 'ax',
 'plottype': 'scatter',
 'x': 1,
 'y': 1,
 'markersize': 5,
 'color': 'darkgray',
 'marker': 'o',
 'vmin': None,
 'vmax': None,
 'alpha': None,
 'linewidths': 1.5,
 'edgecolors': None,
 'label': 'n=1',
 'linear_regression': False,
 'density': False}
```

Running `density_scatter()`:
```
obj.density_scatter()
```
produces
```
{'plot_ax': 'ax',
 'plottype': 'scatter',
 'x': 1,
 'y': 1,
 'markersize': 5,
 'color': 'darkgray',
 'marker': 'o',
 'vmin': None,
 'vmax': None,
 'alpha': None,
 'linewidths': 1.5,
 'edgecolors': None,
 'label': 'n=1',
 'linear_regression': False,
 'density': True,
 'sort': True,
 'cmap': 'magma',
 'colorbar': True,
 'bins': [100, 100]}
```

**Comment by CoryMartin-NOAA** [comment]
@kevindougherty-noaa but what about the option where you do `density=True` for the scatter, it is supposed to call density scatter, but it does not work properly it seems...

**Comment by CoryMartin-NOAA** [comment]
Or are you saying that I need to do `plotobj.density_scatter()` before calling `myplot.draw_data()`?

**Comment by kevindougherty-noaa** [comment]
@CoryMartin-NOAA yes exactly. calling `plotobj.density_scatter()` sets all the settings for you and should be called before `myplot.draw_data()`. Everything needs to be set before drawing the data.
