### ISSUE TITLE
Add function to produce spectrum summary plots

### ISSUE THREAD

**Issue by ADCollard** [NOAA-EMC/emcpy#95]
I think it might be useful to add a function to quickly generate channel-by-channel stats for radiance data.

Input is the data frame produced by the Radiance get_data() method.  Output is a data frame containing channel-by-channel stats.

Useage:

```
from emcpy.stats import spectrum_stats
cs = spectrum_stats(df0)
```

Output is:
```
          count omf_unadjusted_mean omf_adjusted_mean omf_unadjusted_stddev omf_adjusted_stddev
Channel                                                                                        
16       639072          -0.0767162        -0.0767162              0.496137            0.496137
29       638442            0.305489          0.305489              0.441956            0.441956
32       580734            0.314575          0.314575              0.466082            0.466082
35       638316            0.318029          0.318029              0.430345            0.430345
38       593838            0.369614          0.369614              0.436662            0.436662
...         ...                 ...               ...                   ...                 ...
7995      97587            0.044376          0.044376               1.68519             1.68519
8007      97272           0.0490051         0.0490051               1.70388             1.70388
8015      96957              0.1618            0.1618               1.65356             1.65356
8055      96705            0.123651          0.123651               1.66284             1.66284
8078      96894            0.120249          0.120249               1.70867             1.70867
```

cs.plot(subplots=True) produces this:
<img width="626" alt="IASI_Test" src="https://user-images.githubusercontent.com/40322596/154550309-04940818-6743-4c41-aa92-7345ba497c49.png">

Although I find this useful, I am not sure if 
a) It fits into the design of stats.py
b) Its functionality is replicated elsewhere
c) My coding is very pythonic (I mean I have a "for" loop!)

**Comment by ADCollard** [comment]
[Pull request created](https://github.com/NOAA-EMC/emcpy/pull/96).

I should also mention that I have added 
`import pandas as _pd`
to the `stats.py` file.

I am not clear if it was the intention to keep this file pandas free.

**Comment by kevindougherty-noaa** [comment]
Hi @ADCollard, we are going to be transitioning a lot from this repository over to https://github.com/danholdaway/eva. I am going to hold off on reviewing this at the moment as our code sprint is tomorrow. However, I like the capability of this and can see this being pretty useful.

**Comment by ADCollard** [comment]
@kevindougherty-noaa I have moved this issue over to PyGSI as @CoryMartin-NOAA suggested it is better there and I agreed. I assume PyGSI is not included in the eva development?

Closing this issue.
